version: '2'

services:
  api:
    image: 'bookmarker-api'
    build:
      context: ./bookmarker-api
    container_name: api
    ports:
      - 8082:8081
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data

  ui:
    image: bookmarker-ui
    build:
      context: ./bookmarker-ui
      target: dev
      dockerfile: Dockerfile
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_BOOKMARK_URL=http://localhost:8082
    ports:
      - 3000:3000
volumes:
  db:
    driver: local
