apiVersion: v1
kind: Service
metadata:
  name: bookmarker-api-service
spec:
  type: NodePort
  selector:
    app: bookmarker-api
  ports:
    - name: bookmarker-api-port-mapping
      port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 30090
