apiVersion: v1
kind: Service
metadata:
  name: bookmarker-ui-service
spec:
  type: NodePort
  selector:
    app: bookmarker-ui
  ports:
    - name: bookmarker-ui-port-mapping
      port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 30030
