name: API build
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
    paths:
      - "bookmarker-api/**"
jobs:
  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4
      # test
      - name: Run build
        run: make build
